server: 
    port: 18080

spring:
    datasource:
        db1:
            username: root
            password: 123456
            jdbc-url: jdbc:mysql://114.115.160.23:13306/db_test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
            driver-class-name: com.mysql.cj.jdbc.Driver
        db2:
            # HikariPool-1 - jdbcUrl is required with driverClassName.
            # 单数据源用url，多数据源用jdbc-url
            jdbc-url: jdbc:ignite:thin://localhost:10800/PUBLIC
            driver-class-name: org.apache.ignite.IgniteJdbcThinDriver
        druid:
            initial-size: 1
            max-active: 20
            min-idle: 1
            max-wait: 60000
    autoconfigure:
        #DruidDataSourceAutoConfigure会注入一个DataSourceWrapper，其会在原生的spring.datasource下找 url, username, password 等。动态数据源 URL 等配置是在 dynamic 下，因此需要排除，否则会报错
        exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure 

mybatis:
    mapper-locations: classpath:mapping/db1/*Mapper.xml
    type-aliases-package: com.example.db.entity

logging:
    level:
        com:
            example:
                mapper: debug